### PR TITLE
feat(l10n): add Persian (Farsi) locale

### PR DESCRIPTION
**Pull request by o-mid**
## Summary
- Adds `fa` as a new supported locale (additive; does not change existing languages).
- Ships `app_fa.arb` with full UI string coverage and `app_localizations_ext_fa.dart` for agent prompts, OAuth copy, and default characters.
- Registers Farsi in `supported_languages.dart` and adds locale lookup smoke tests.

## Test plan
- [x] `flutter gen-l10n`
- [x] `dart analyze lib/l10n/ test/l10n/locale_lookup_test.dart`
- [x] `flutter test test/l10n/locale_lookup_test.dart` (blocked locally by `sherpa_onnx` pub resolution)
- [x] Switch app language to فارسی in Settings and spot-check Settings, chat, and timeline strings
- [x] Verify RTL layout renders correctly for Farsi (same direction family as Arabic)

cc @sparkleMing @whbzju for review when convenient.

### CODE REVIEW

**Review by sparkleMing — CHANGES_REQUESTED** [review]
Blocking after #412 landed on main: this locale does not implement the newly added ARB keys (`commentAuthorUser`, `commentAuthorAi`, `authorizationCancelled`, `timelineWeekNumberLabel`, `timelineWeekLabel`, `eventCardDefaultTitle`, `memoryNoLongTermYet`, `memoryNoRecentBuffer`, and `memoryGeneralSubject`). The current green CI was run against the older base, so merging now would leave the generated locale subclass missing abstract getters and break compilation. Please rebase/merge latest main, translate these keys in this locale's ARB, rerun `flutter gen-l10n`, and rerun the locale lookup/full Flutter checks.

**Review by sparkleMing — APPROVED** [review]
Updated to latest main, added the localization keys introduced by #412, regenerated the Farsi localization class, and verified the targeted l10n tests plus static analysis locally.
